//MEALS
//FETCH 
export const FETCH_MEALS = 'FETCH_MEALS';
export const FETCH_M_SUCCESS = 'FETCH_M_SUCCESS';
export const FETCH_M_FAIL = 'FETCH_M_FAIL';
//ADD
export const ADD_MEAL = 'ADD_MEAL';
//DELETE
export const DELETE_MEAL = 'DELETE_MEAL';
export const DELETE_M_SUCCESS = 'DELETE_M_SUCCESS';
//GROCERIES
//FETCH
export const FETCH_GROCERIES = 'FETCH_GROCERIES';
export const FETCH_G_SUCCESS = 'FETCH_G_SUCCESS';
export const FETCH_G_FAIL = 'FETCH_FG_AIL'; 
//ADD
export const ADD_GROCERY = 'ADD_GROCERY';
//DELETE
export const DELETE_GROCERY = 'DELETE_GROCERY';
export const DELETE_G_SUCCESS = 'DELETE_G_SUCCESS';