//MEALS
//FETCH 
export const FETCH_MEALS = 'FETCH_MEALS';
export const FETCH_MEAL_GROCERIES ='FETCH_MEAL_GROCERIES'

//ADD
export const ADD_MEAL = 'ADD_MEAL';
export const ADD_GROCERIES_TO_MEAL = 'ADD_GROCERIES_TO_MEAL';

//DELETE
export const DELETE_MEAL = 'DELETE_MEAL';

//GROCERIES
//FETCH
export const FETCH_GROCERIES = 'FETCH_GROCERIES';
 
//ADD
export const ADD_GROCERY = 'ADD_GROCERY';
//DELETE
export const DELETE_GROCERY = 'DELETE_GROCERY';
